lang: zh-CN
title: Lighter
email: 
description: "从量变到质变，致力于观蓝光星球如庵摩罗果"

url: http://amlgx.com
author:
  name: 光武中兴
  picture: 
github_username: 
name: Lighter
logo: /img/favicon.ico
timezone: Asia/Shanghai

# Build settings
theme: jekyll-theme-cayman
markdown: kramdown
highlighter: rouge

plugins: 
#  - jekyll-sitemap
  - jekyll-paginate

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Exclude from processing.
exclude: 
  - draft

